[package]
name = "rip"
version = "0.1.0"
edition = "2024"
authors = ["Tom Rooker", "Claude.AI"]


[dependencies]
flate2 = { version = "1.0", features = ["rust_backend"] }
serde = { version = "1.0", features = ["derive"] }
rusqlite = "0.35.0"
rand = "0.8"
rayon = "1.8"
indicatif = "0.17"
ctrlc = "3"
noise = "0.9"
rustfft = "6.2"
num-complex = "0.4"
crossterm = "0.27"
