// @generated by generate_entities.py from template.db
// Do not edit by hand - change the column in the database and regenerate.

#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct Cell {
    /// Unique identifier for this cell in the database
    pub cell_id: i64,
    /// Foreign key to the cell_position table
    pub cell_position_id: i64,
    /// Simulation timestep at which this cell state was recorded
    pub timestep: usize,
    /// Z-layer index within the 3D grid
    pub layer: usize,
    /// Local curvature of spacetime at this cell
    pub curvature: f64,
    /// Mass density of matter within the cell
    pub matter_density: f64,
    /// True if this cell has collapsed into a black hole
    pub is_black_hole: bool,
    /// Strength of the rip field in this cell
    pub rip_strength: f64,
    /// Id of the linked black hole; legitimately NULL for non-BH cells
    pub black_hole_id: Option<u64>,
    /// Cosmological scale factor at this timestep
    pub scale_factor: f64,
    /// X-component of the gravitational vector at this cell
    pub gravity_x: f64,
    /// Y-component of the gravitational vector at this cell
    pub gravity_y: f64,
    /// Z-component of the gravitational vector at this cell
    pub gravity_z: f64,
    /// Calculated per cell after inflation (can be negative)
    pub dimple_strength: f64,
    /// Ff strong dimple + low matter density
    pub is_lensing_candidate: bool,
    /// Is this cell is an SMBH (mass exceeds threshold)
    pub is_supermassive: bool,
    /// Total mass in the cell
    pub mass: f64,
    /// The amount this cell contributes to the dark energy rip field
    pub smbh_rip_contribution: bool,
    /// True if this black hole was created due to rip-induced collapse (not from natural matter collapse)
    pub is_rip_induced: bool,
    pub run_id: i64,
    /// Per-SMBH parent-connection feed rate, assigned at formation from the heavy-tailed draw. Most SMBHs get a near-zero value (they stall); a rare few get a strong connection and run away to overmassive scale. Zero for non-SMBH cells.
    pub smbh_connection_strength: f64,
    /// True if this cell contains a star.
    pub is_star: bool,
    /// ID of the galaxy this cell belongs to.
    pub galaxy_id: i64,
    /// The amount this cell's dimple contributes to the overall gravity, calculated after inflation.
    pub rip_dimple: f64,
    /// Physical volume of the cell in simulated space
    pub volume: f64,
}

impl Cell {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            cell_id: 0,
            cell_position_id: 0,
            timestep: 0,
            layer: 0,
            curvature: 0.0,
            matter_density: 0.0,
            is_black_hole: false,
            rip_strength: 0.0,
            black_hole_id: None,
            scale_factor: 0.0,
            gravity_x: 0.0,
            gravity_y: 0.0,
            gravity_z: 0.0,
            dimple_strength: 0.0,
            is_lensing_candidate: false,
            is_supermassive: false,
            mass: 0.0,
            smbh_rip_contribution: false,
            is_rip_induced: false,
            run_id: 0,
            smbh_connection_strength: 0.0,
            is_star: false,
            galaxy_id: 0,
            rip_dimple: 0.0,
            volume: 1.0,
        }
    }
}
