// @generated by generate_entities.py from template.db
// Do not edit by hand - change the column in the database and regenerate.

/// Fixed (col, row) grid coordinate a cell_position_id maps to; the per-timestep state and the layer live on the cell row. Decouples position from state so positions are stored once.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CellPosition {
    pub cell_position_id: i64,
    pub col: usize,
    pub row: usize,
}

impl CellPosition {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            cell_position_id: 0,
            col: 0,
            row: 0,
        }
    }
}
