// @generated by generate_entities.py from template.db
// Do not edit by hand - change the column in the database and regenerate.

#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct CustomDensity {
    pub col: i64,
    pub row: i64,
    pub layer: i64,
    pub density: f64,
}

impl CustomDensity {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            col: 0,
            row: 0,
            layer: 0,
            density: 0.0,
        }
    }
}
