// @generated by generate_entities.py from template.db
// Do not edit by hand - change the column in the database and regenerate.

/// One row per galaxy identified in a run: formation timestep, current centroid, radius, mass breakdown (total / stellar / SMBH), cell count, and whether it is still active.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct Galaxy {
    pub galaxy_id: i64,
    pub run_id: i64,
    pub formed_timestep: i64,
    pub centroid_col: f64,
    pub centroid_row: f64,
    pub centroid_layer: f64,
    pub radius: f64,
    pub total_mass: f64,
    pub stellar_mass: f64,
    pub smbh_mass: f64,
    pub cell_count: i64,
    pub is_active: bool,
}

impl Galaxy {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            galaxy_id: 0,
            run_id: 0,
            formed_timestep: 0,
            centroid_col: 0.0,
            centroid_row: 0.0,
            centroid_layer: 0.0,
            radius: 0.0,
            total_mass: 0.0,
            stellar_mass: 0.0,
            smbh_mass: 0.0,
            cell_count: 0,
            is_active: true,
        }
    }
}
