// @generated by generate_entities.py from template.db
// Do not edit by hand - change the column in the database and regenerate.

/// Time series of per-galaxy properties (mass breakdown, centroid, radius, cell and SMBH counts) sampled each recorded timestep; the history behind the galaxy summary.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct GalaxyTimestep {
    pub galaxy_id: i64,
    pub timestep: i64,
    pub total_mass: f64,
    pub stellar_mass: f64,
    pub smbh_mass: f64,
    pub cell_count: i64,
    pub smbh_count: i64,
    pub radius: f64,
    pub centroid_col: f64,
    pub centroid_row: f64,
    pub centroid_layer: f64,
}

impl GalaxyTimestep {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            galaxy_id: 0,
            timestep: 0,
            total_mass: 0.0,
            stellar_mass: 0.0,
            smbh_mass: 0.0,
            cell_count: 0,
            smbh_count: 0,
            radius: 0.0,
            centroid_col: 0.0,
            centroid_row: 0.0,
            centroid_layer: 0.0,
        }
    }
}
