// @generated by generate_entities.py from template.db
// Do not edit by hand - change the column in the database and regenerate.

#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct Log {
    pub id: i64,
    pub timestamp: f64,
    pub module: String,
    pub level: String,
    pub message: String,
    pub run_id: i64,
}

impl Log {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            id: 0,
            timestamp: 0.0,
            module: String::new(),
            level: String::new(),
            message: String::new(),
            run_id: 0,
        }
    }
}
