// @generated by generate_entities.py from template.db
// Do not edit by hand - change the column in the database and regenerate.

/// Adjacency list between cells with precomputed distance, used for spatial transport and gravity neighbor lookups.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct Neighbor {
    pub neighbor_id: i64,
    pub cell_id: i64,
    pub neighbor_cell_id: i64,
    pub distance: f64,
}

impl Neighbor {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            neighbor_id: 0,
            cell_id: 0,
            neighbor_cell_id: 0,
            distance: 0.0,
        }
    }
}
