// @generated by generate_entities.py from template.db
// Do not edit by hand - change the column in the database and regenerate.

/// One row per simulation run: start/end times, status, RNG seed, git commit, and free-text notes. The parent that every run-scoped table references via run_id.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct Run {
    pub run_id: i64,
    pub started_at: String,
    /// NULL until run completes
    pub ended_at: Option<String>,
    pub status: String,
    pub seed: u64,
    /// optional
    pub git_commit: Option<String>,
    /// optional free-form
    pub notes: Option<String>,
}

impl Run {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            run_id: 0,
            started_at: String::new(),
            ended_at: None,
            status: String::new(),
            seed: 0,
            git_commit: None,
            notes: None,
        }
    }
}
