// @generated by generate_entities.py from template.db
// Do not edit by hand - change the column in the database and regenerate.

/// Snapshot of the app_setting values actually used for a given run (key/value/datatype per run_id), so a run's parameters stay reproducible independent of later template edits.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct RunSetting {
    pub run_id: i64,
    pub key: String,
    pub value: String,
    pub datatype: String,
}

impl RunSetting {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            run_id: 0,
            key: String::new(),
            value: String::new(),
            datatype: String::new(),
        }
    }
}
