// @generated by generate_entities.py from template.db
// Do not edit by hand - change the column in the database and regenerate.

/// Tracer/structure particles carrying position and velocity per recorded time; the substrate the Tier 2 collisionless dark-matter particle-mesh builds on (mass field is the Tier 2 addition).
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct StructureParticle {
    pub structure_particle_id: i64,
    pub time: f64,
    pub rip_strength: f64,
    pub scale_factor: f64,
    pub position_x: f64,
    pub position_y: f64,
    pub position_z: f64,
    pub velocity_x: f64,
    pub velocity_y: f64,
    pub velocity_z: f64,
    pub run_id: i64,
}

impl StructureParticle {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            structure_particle_id: 0,
            time: 0.0,
            rip_strength: 0.0,
            scale_factor: 0.0,
            position_x: 0.0,
            position_y: 0.0,
            position_z: 0.0,
            velocity_x: 0.0,
            velocity_y: 0.0,
            velocity_z: 0.0,
            run_id: 0,
        }
    }
}
