// @generated by generate_entities.py from template.db
// Do not edit by hand - change the column in the database and regenerate.

/// One row per timestep of global scalars: total matter (non-BH cells), scale factor, average rip strength and gravity, and black-hole / SMBH / star / galaxy counts. Source for the inflation, matter, and galaxy-count plots.
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct TimestepSummary {
    pub timestep: i64,
    pub time_myr: f64,
    pub rip_strength_avg: f64,
    pub scale_factor: f64,
    pub run_id: i64,
    pub total_matter: f64,
    pub black_hole_count: i64,
    pub gravity_magnitude_avg: f64,
    pub smbh_count: i64,
    pub star_count: i64,
    pub galaxy_count: i64,
}

impl TimestepSummary {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self {
            timestep: 0,
            time_myr: 0.0,
            rip_strength_avg: 0.0,
            scale_factor: 0.0,
            run_id: 0,
            total_matter: 0.0,
            black_hole_count: 0,
            gravity_magnitude_avg: 0.0,
            smbh_count: 0,
            star_count: 0,
            galaxy_count: 0,
        }
    }
}
