"""
db_to_markdown.py - Generate a markdown schema reference from a SQLite database.

For every table it emits: the table-level description (the /* ... */ comment
after the column-list close paren, written by set_table_descriptions.py) and a
column table with declared type, nullability, key, default, and the column's
/* ... */ doc comment. Pure read - never writes to the database.

Usage:
    python db_to_markdown.py template.db --out documents/schema.md
    python db_to_markdown.py template.db            # -> <db stem>_schema.md
"""

import argparse
import re
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path


# ---- comment parsing (kept standalone so this script has no local imports) ----

def column_list_close(sql):
    """Index of the ')' closing the column-list '(', skipping comments/strings."""
    n = len(sql)
    i = sql.find("(")
    if i < 0:
        return -1
    i += 1
    depth = 1
    while i < n:
        ch = sql[i]
        if ch == "/" and i + 1 < n and sql[i + 1] == "*":
            j = sql.find("*/", i + 2)
            i = (n if j < 0 else j + 2)
            continue
        if ch == "-" and i + 1 < n and sql[i + 1] == "-":
            j = sql.find("\n", i + 2)
            i = (n if j < 0 else j)
            continue
        if ch in "'\"":
            j = sql.find(ch, i + 1)
            i = (n if j < 0 else j + 1)
            continue
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return -1


def parse_table_comment(sql):
    close = column_list_close(sql)
    if close < 0:
        return ""
    m = re.search(r"/\*(.*?)\*/", sql[close + 1:], flags=re.S)
    return " ".join(m.group(1).split()) if m else ""


# Column comment parser - same logic as generate_entities.parse_column_comments,
# so the two stay in agreement about which comment belongs to which column.
_SKIP_TOKENS = {"PRIMARY", "FOREIGN", "UNIQUE", "CHECK", "CONSTRAINT", "KEY"}


def parse_column_comments(create_sql):
    if not create_sql:
        return {}
    s, n = create_sql, len(create_sql)
    i = s.find("(")
    if i < 0:
        return {}
    i += 1
    depth, buf, cur, segs = 1, [], [], []

    def flush():
        segs.append(["".join(buf), cur])

    def attach(t):
        (segs[-1][1] if "".join(buf).strip() == "" and segs else cur).append(t)

    while i < n and depth > 0:
        ch = s[i]
        if ch == "/" and i + 1 < n and s[i + 1] == "*":
            j = s.find("*/", i + 2)
            j = n if j < 0 else j
            attach(s[i + 2:j].strip())
            i = j + 2
            continue
        if ch == "-" and i + 1 < n and s[i + 1] == "-":
            j = s.find("\n", i + 2)
            j = n if j < 0 else j
            attach(s[i + 2:j].strip())
            i = j
            continue
        if ch == "(":
            depth += 1
            buf.append(ch)
        elif ch == ")":
            depth -= 1
            if depth == 0:
                flush()
                break
            buf.append(ch)
        elif ch == "," and depth == 1:
            flush()
            buf, cur = [], []
        else:
            buf.append(ch)
        i += 1
    out = {}
    for code, cmts in segs:
        cmts = [c for c in cmts if c]
        if not cmts:
            continue
        m = re.match(r'[\s"`\[]*([A-Za-z_]\w*)', code.strip())
        if m and m.group(1).upper() not in _SKIP_TOKENS:
            out[m.group(1)] = " ".join(" ".join(cmts).split())
    return out


# ---- rendering -------------------------------------------------------------

def md_escape(text):
    return text.replace("|", "\\|") if text else ""


def render(db_path):
    conn = sqlite3.connect(db_path)
    tables = conn.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY name").fetchall()

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    out = [f"# Schema reference - `{db_path.name}`", ""]
    out.append(f"*Generated by `db_to_markdown.py` on {stamp}. "
               f"Do not edit by hand - change the database and regenerate.*")
    out.append("")
    out.append(f"{len(tables)} tables: " +
               ", ".join(f"[`{t[0]}`](#{t[0]})" for t in tables))
    out.append("")

    for name, sql in tables:
        col_comments = parse_column_comments(sql)
        table_desc = parse_table_comment(sql)
        cols = conn.execute(f'PRAGMA table_info("{name}")').fetchall()

        out.append(f"## {name}")
        out.append("")
        out.append(table_desc if table_desc else "_No table description._")
        out.append("")
        out.append("| Column | Type | Null | Key | Default | Description |")
        out.append("| --- | --- | --- | --- | --- | --- |")
        for cid, col, ctype, notnull, dflt, pk in cols:
            typ = ctype if ctype else ""
            nullable = "NOT NULL" if notnull else "NULL"
            key = f"PK{pk}" if pk else ""           # PK1/PK2... shows composite order
            default = "" if dflt is None else str(dflt)
            desc = md_escape(col_comments.get(col, ""))
            out.append(f"| `{col}` | {typ} | {nullable} | {key} | "
                       f"{md_escape(default)} | {desc} |")
        out.append("")

    conn.close()
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("db")
    ap.add_argument("--out", help="output markdown path "
                                  "(default: <db stem>_schema.md)")
    args = ap.parse_args(argv)

    db_path = Path(args.db)
    if not db_path.exists():
        print(f"error: {db_path} not found", file=sys.stderr)
        return 1

    out_path = Path(args.out) if args.out else db_path.with_name(
        f"{db_path.stem}_schema.md")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(db_path), encoding="utf-8")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())