#!/usr/bin/env python3
"""
generate_entities.py - Generate Rust entity structs from a SQLite database.

One file per table (snake_case table -> snake_case .rs, PascalCase struct).
Column types come from the declared type; column /* */ comments become ///
doc comments. Prototype of what build.rs will do at compile time.

Type mapping:
  * A declared type that is already a Rust type (i64, u64, usize, f64, bool,
    String, ...) is emitted verbatim - declare a column that way to pin it.
  * Otherwise: INTEGER-ish -> i64, REAL/NUMERIC -> f64, TEXT/CHAR -> String,
    BOOLEAN -> bool, BLOB -> Vec<u8>.
  * Non-PK column without NOT NULL becomes Option<T>.
  * --bool-prefixes maps integer columns with the given name prefixes to bool
    (a no-DDL-change alternative to declaring the column BOOLEAN).

Usage:
    python generate_entities.py template.db --out-dir generated --mod-rs
    python generate_entities.py template.db --out-dir generated --with-new \\
        --bool-prefixes is_ \\
        --derive-for cell_position=Debug,Clone,PartialEq,Eq,Hash
"""

import argparse
import re
import sqlite3
import sys
from pathlib import Path

_SKIP_TOKENS = {"PRIMARY", "FOREIGN", "UNIQUE", "CHECK", "CONSTRAINT", "KEY"}
_RUST_INTS = {"i8", "i16", "i32", "i64", "i128", "isize",
              "u8", "u16", "u32", "u64", "u128", "usize"}
_RUST_FLOATS = {"f32", "f64"}
_RUST_TYPES = _RUST_INTS | _RUST_FLOATS | {"bool", "String"}


def parse_column_comments(create_sql):
    if not create_sql:
        return {}
    s, n = create_sql, len(create_sql)
    i = s.find("(")
    if i < 0:
        return {}
    i += 1
    depth, buf, cur, segs = 1, [], [], []

    def flush():
        segs.append(["".join(buf), cur])

    def attach(t):
        (segs[-1][1] if "".join(buf).strip() == "" and segs else cur).append(t)

    while i < n and depth > 0:
        ch = s[i]
        if ch == "/" and i + 1 < n and s[i + 1] == "*":
            j = s.find("*/", i + 2)
            j = n if j < 0 else j
            attach(s[i + 2:j].strip())
            i = j + 2
            continue
        if ch == "-" and i + 1 < n and s[i + 1] == "-":
            j = s.find("\n", i + 2)
            j = n if j < 0 else j
            attach(s[i + 2:j].strip())
            i = j
            continue
        if ch == "(":
            depth += 1
            buf.append(ch)
        elif ch == ")":
            depth -= 1
            if depth == 0:
                flush()
                break
            buf.append(ch)
        elif ch == "," and depth == 1:
            flush()
            buf, cur = [], []
        else:
            buf.append(ch)
        i += 1
    out = {}
    for code, cmts in segs:
        cmts = [c for c in cmts if c]
        if not cmts:
            continue
        m = re.match(r'[\s"`\[]*([A-Za-z_]\w*)', code.strip())
        if m and m.group(1).upper() not in _SKIP_TOKENS:
            out[m.group(1)] = " ".join(cmts)
    return out


def rust_type(decl, warnings, table, col, bool_prefixes=()):
    d = (decl or "").strip()
    if d in _RUST_TYPES:
        return d
    u = d.upper()
    if "INT" in u:
        if any(col.startswith(p) for p in bool_prefixes):
            return "bool"
        return "i64"
    if "BOOL" in u:
        return "bool"
    if any(k in u for k in ("REAL", "FLOA", "DOUB", "NUMERIC", "DECIMAL")):
        return "f64"
    if any(k in u for k in ("CHAR", "CLOB", "TEXT", "STRING")):
        return "String"
    if "BLOB" in u:
        return "Vec<u8>"
    warnings.append(f"{table}.{col}: unrecognized type '{decl}', defaulting to i64")
    return "i64"


def pascal_case(name):
    return "".join(p.capitalize() for p in name.split("_"))


def default_expr(base, is_option, dflt):
    if is_option:
        return "None"
    raw = "" if dflt is None else str(dflt).strip()
    if raw != "":
        lit = raw.strip("'\"")
        if base == "bool":
            return "true" if lit.lower() in ("1", "true") else "false"
        if base in _RUST_INTS:
            return lit
        if base in _RUST_FLOATS:
            # a float field must get a float literal even if the DB default
            # was written as an integer (DEFAULT 0 -> 0.0)
            return f"{lit}.0" if re.fullmatch(r"-?\d+", lit) else lit
        if base == "String":
            return f'"{lit}".to_string()' if lit else "String::new()"
    if base == "bool":
        return "false"
    if base in _RUST_INTS:
        return "0"
    if base in _RUST_FLOATS:
        return "0.0"
    if base == "String":
        return "String::new()"
    if base.startswith("Vec<"):
        return "Vec::new()"
    return "Default::default()"


HEADER = (
    "// @generated by generate_entities.py from {db}\n"
    "// Do not edit by hand - change the column in the database and regenerate.\n\n"
)


def generate_struct(db_name, table, columns, comments, derives,
                    warnings, bool_prefixes, with_new):
    name = pascal_case(table)
    out = [HEADER.format(db=db_name).rstrip("\n"), ""]
    out.append("#[allow(dead_code)]")
    out.append(f"#[derive({', '.join(derives)})]")
    out.append(f"pub struct {name} {{")
    fields = []  # (col, base_type, is_option, dflt)
    for cid, col, ctype, notnull, dflt, pk in columns:
        base = rust_type(ctype, warnings, table, col, bool_prefixes)
        is_option = (not pk) and (not notnull)
        ty = f"Option<{base}>" if is_option else base
        c = comments.get(col)
        if c:
            out.append(f"    /// {c}")
        out.append(f"    pub {col}: {ty},")
        fields.append((col, base, is_option, dflt))
    out.append("}")
    if with_new:
        out.append("")
        out.append(f"impl {name} {{")
        out.append("    #[allow(dead_code)]")
        out.append("    pub fn new() -> Self {")
        out.append("        Self {")
        for col, base, is_option, dflt in fields:
            out.append(f"            {col}: {default_expr(base, is_option, dflt)},")
        out.append("        }")
        out.append("    }")
        out.append("}")
    out.append("")
    return "\n".join(out)


def write_if_changed(path, content):
    """Write content only if it differs from what's on disk.

    Avoids bumping the file mtime when nothing changed, so regeneration does
    not trigger spurious cargo rebuilds or dirty the working tree.
    """
    try:
        if path.exists() and path.read_text(encoding="utf-8") == content:
            return False
    except OSError:
        pass
    path.write_text(content, encoding="utf-8")
    return True


def get_tables(conn):
    return conn.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("db")
    ap.add_argument("--out-dir", default="generated")
    ap.add_argument("--skip-tables", nargs="*", default=["app_setting"])
    ap.add_argument("--derive", default="Debug,Clone",
                    help="default derives applied to each struct")
    ap.add_argument("--derive-for", action="append", default=[],
                    metavar="TABLE=D1,D2",
                    help="per-table derive override (repeatable)")
    ap.add_argument("--bool-prefixes", nargs="*", default=[],
                    help="integer columns with these name prefixes -> bool")
    ap.add_argument("--with-new", action="store_true",
                    help="also generate impl new() honoring column defaults")
    ap.add_argument("--extra-mods", nargs="*", default=[],
                    help="hand-written modules in THIS dir to keep in mod.rs")
    ap.add_argument("--mod-rs", action="store_true")
    args = ap.parse_args(argv)

    db_path = Path(args.db)
    if not db_path.exists():
        print(f"error: {db_path} not found", file=sys.stderr)
        return 1

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    default_derives = [d.strip() for d in args.derive.split(",") if d.strip()]
    overrides = {}
    for spec in args.derive_for:
        if "=" not in spec:
            print(f"error: --derive-for needs TABLE=D1,D2 (got '{spec}')",
                  file=sys.stderr)
            return 1
        tbl, ds = spec.split("=", 1)
        overrides[tbl.strip()] = [d.strip() for d in ds.split(",") if d.strip()]
    skip = set(args.skip_tables)

    conn = sqlite3.connect(db_path)
    warnings, generated, changed = [], [], 0
    for table, sql in get_tables(conn):
        if table in skip:
            continue
        columns = conn.execute(f'PRAGMA table_info("{table}")').fetchall()
        if not columns:
            continue
        derives = overrides.get(table, default_derives)
        code = generate_struct(db_path.name, table, columns,
                               parse_column_comments(sql), derives,
                               warnings, args.bool_prefixes, args.with_new)
        path = out_dir / f"{table}.rs"
        if write_if_changed(path, code):
            print(f"wrote {path}")
            changed += 1
        else:
            print(f"unchanged {path}")
        generated.append(table)
    conn.close()

    if args.mod_rs:
        mods = sorted(set(generated) | set(args.extra_mods))
        body = HEADER.format(db=db_path.name)
        body += "\n".join(f"pub mod {m};" for m in mods) + "\n"
        mod_path = out_dir / "mod.rs"
        if write_if_changed(mod_path, body):
            print(f"wrote {mod_path}")
            changed += 1
        else:
            print(f"unchanged {mod_path}")

    print(f"{changed} file(s) changed")
    for w in warnings:
        print(f"  warning: {w}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())