[package]
name = "rip-post"
version = "0.1.0"
edition = "2024"

[dependencies]
rip-core = { path = "../rip-core" }
flate2 = "1"
csv = "1"
serde = { version = "1", features = ["derive"] }
indicatif = "0.17"
